#!/bin/sh
set -eux

pytest supa_auth/tests
pytest --reuse-db --no-migrations supa_auth/tests
PYTHONPATH=. pytest examples/onlydb/tests
PYTHONPATH=. pytest examples/localdb/tests
PYTHONPATH=. pytest examples/remotedb/tests
